"""baseline schema

Revision ID: 8455adbbd969
Revises:
Create Date: 2026-06-17 17:20:29.523937

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8455adbbd969"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("activity_id", sa.String(), nullable=False),
        sa.Column("start_date_time", sa.DateTime(), nullable=False),
        sa.Column("sport_type", sa.String(), nullable=False),
        sa.Column("activity_type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("elevation_m", sa.Float(), nullable=False),
        sa.Column("moving_time_s", sa.Integer(), nullable=False),
        sa.Column("elapsed_time_s", sa.Integer(), nullable=False),
        sa.Column("average_speed_ms", sa.Float(), nullable=True),
        sa.Column("max_speed_ms", sa.Float(), nullable=True),
        sa.Column("average_heart_rate", sa.Integer(), nullable=True),
        sa.Column("max_heart_rate", sa.Integer(), nullable=True),
        sa.Column("average_cadence", sa.Integer(), nullable=True),
        sa.Column("max_cadence", sa.Integer(), nullable=True),
        sa.Column("average_power", sa.Integer(), nullable=True),
        sa.Column("max_power", sa.Integer(), nullable=True),
        sa.Column("normalized_power", sa.Float(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("start_latitude", sa.Float(), nullable=True),
        sa.Column("start_longitude", sa.Float(), nullable=True),
        sa.Column("polyline", sa.String(), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("device_name", sa.String(), nullable=True),
        sa.Column("gear_id", sa.String(), nullable=True),
        sa.Column("gear_name", sa.String(), nullable=True),
        sa.Column("is_commute", sa.Boolean(), nullable=False),
        sa.Column("workout_type", sa.String(), nullable=True),
        sa.Column("import_source", sa.String(), nullable=False),
        sa.Column("streams_are_imported", sa.Boolean(), nullable=False),
        sa.Column("source_hash", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("activity_id"),
    )
    with op.batch_alter_table("activity", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_activity_type"), ["activity_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_activity_gear_id"), ["gear_id"], unique=False)
        batch_op.create_index(
            "ix_activity_sport_start", ["sport_type", "start_date_time"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_activity_sport_type"), ["sport_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_activity_start_date_time"), ["start_date_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_streams_are_imported"), ["streams_are_imported"], unique=False
        )
        batch_op.create_index(
            "ix_activity_type_start", ["activity_type", "start_date_time"], unique=False
        )

    op.create_table(
        "activity_stream",
        sa.Column("activity_id", sa.String(), nullable=False),
        sa.Column("stream_type", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("activity_id", "stream_type"),
    )
    with op.batch_alter_table("activity_stream", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_stream_activity_id"), ["activity_id"], unique=False
        )

    op.create_table(
        "best_effort",
        sa.Column("activity_id", sa.String(), nullable=False),
        sa.Column("distance_m", sa.Integer(), nullable=False),
        sa.Column("sport_type", sa.String(), nullable=False),
        sa.Column("activity_type", sa.String(), nullable=False),
        sa.Column("start_date_time", sa.DateTime(), nullable=False),
        sa.Column("time_s", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("activity_id", "distance_m"),
    )
    with op.batch_alter_table("best_effort", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_best_effort_activity_id"), ["activity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_best_effort_activity_type"), ["activity_type"], unique=False
        )
        batch_op.create_index(
            "ix_best_effort_lookup", ["activity_type", "distance_m", "time_s"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_best_effort_sport_type"), ["sport_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_best_effort_start_date_time"), ["start_date_time"], unique=False
        )

    op.create_table(
        "gear",
        sa.Column("gear_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("gear_type", sa.String(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("is_retired", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("gear_id"),
    )
    op.create_table(
        "import_run",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("activities_added", sa.Integer(), nullable=False),
        sa.Column("activities_updated", sa.Integer(), nullable=False),
        sa.Column("activities_skipped", sa.Integer(), nullable=False),
        sa.Column("gear_upserted", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("import_run")
    op.drop_table("gear")
    with op.batch_alter_table("best_effort", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_best_effort_start_date_time"))
        batch_op.drop_index(batch_op.f("ix_best_effort_sport_type"))
        batch_op.drop_index("ix_best_effort_lookup")
        batch_op.drop_index(batch_op.f("ix_best_effort_activity_type"))
        batch_op.drop_index(batch_op.f("ix_best_effort_activity_id"))

    op.drop_table("best_effort")
    with op.batch_alter_table("activity_stream", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_stream_activity_id"))

    op.drop_table("activity_stream")
    with op.batch_alter_table("activity", schema=None) as batch_op:
        batch_op.drop_index("ix_activity_type_start")
        batch_op.drop_index(batch_op.f("ix_activity_streams_are_imported"))
        batch_op.drop_index(batch_op.f("ix_activity_start_date_time"))
        batch_op.drop_index(batch_op.f("ix_activity_sport_type"))
        batch_op.drop_index("ix_activity_sport_start")
        batch_op.drop_index(batch_op.f("ix_activity_gear_id"))
        batch_op.drop_index(batch_op.f("ix_activity_activity_type"))

    op.drop_table("activity")
    # ### end Alembic commands ###
